### PR TITLE
Fixed bottom scrollbar issue on / route

### LINKED ISSUE #212: Small Layout Shift
### Description

There's a small layout shift when navigating away from the `/` route to `/docs` or `/login`

It's caused by the scrollbar. I'm not sure if there's a way to get around this thouhg

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by arun-kushwaha04**
## Fixes Issue
Closes #212 

## Changes proposed
Currently there is bottom scroll bar on `/` route while, it doesn't appears on other routes such as `/docs` or `/login`.

Botton Scrollbar on `/` route

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
Fixed scroll bar issue

### CODE REVIEW

File: src/routes/+layout.svelte [hunk 1]
```diff
@@ -13,7 +13,7 @@
 </script>
 
 <QueryClientProvider client={data.queryClient}>
-  <div class="flex min-h-screen flex-col">
+  <div class="flex min-h-screen flex-col overflow-hidden">
```
Comment (Cahllagerfeld) [inline src/routes/+layout.svelte:16]: I'm not sure if we should add `overflow-hidden` to the layout and therefor the entire app, or if we should scope the hidden overflow to the one route that is affected only. What do you think?

Comment (arun-kushwaha04) [reply src/routes/+layout.svelte:16]: I don't think specifying overflow-hidden in layout will cause any problem in UI. Moreover we can add `overflow-x-hidden` instead of `overflow-hidden`, so it only hides the scroll bar in x-axis.

**Review by Cahllagerfeld — APPROVED** [review]
I think we should merge it for now 👍
